language: generic
dist: trusty

before_install:
  # g++ 6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Qt 5.6.3
  - sudo add-apt-repository -y ppa:beineri/opt-qt563-trusty

  # Update
  - sudo apt-get -y update

install:
  # g++ 6
  - sudo apt-get install -y g++-6

  # Qt 5.6.3
  - sudo apt-get install -y qt56base

before_script:
  # g++ 6
  - export CC="gcc-6"
  - export CXX="g++-6"

  # Qt 5.6.3
  - QTDIR="/opt/qt56"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt56/bin/qt56-env.sh

  # Python 3.6
  - pyenv global 3.6

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
